### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by danboid** [flaviozavan/uzebox-patch-studio#4]
Debian testing, gcc (Debian 12.2.0-14) 12.2.0, libwxgtk3.2-dev 3.2.2+dfsg-2

```
dan@zbook:~/src/uzebox-patch-studio$ make
g++ -Wall -Wextra -O2 `wx-config --cflags` `sdl2-config --cflags` `pkg-config --cflags SDL2_mixer` -std=c++14   -c -o upsgrid.o upsgrid.cpp
g++ -Wall -Wextra -O2 `wx-config --cflags` `sdl2-config --cflags` `pkg-config --cflags SDL2_mixer` -std=c++14   -c -o filereader.o filereader.cpp
g++ -Wall -Wextra -O2 `wx-config --cflags` `sdl2-config --cflags` `pkg-config --cflags SDL2_mixer` -std=c++14   -c -o patchdata.o patchdata.cpp
g++ -Wall -Wextra -O2 `wx-config --cflags` `sdl2-config --cflags` `pkg-config --cflags SDL2_mixer` -std=c++14   -c -o structdata.o structdata.cpp
g++ -Wall -Wextra -O2 `wx-config --cflags` `sdl2-config --cflags` `pkg-config --cflags SDL2_mixer` -std=c++14    uzebox-patch-studio.cpp upsgrid.o filereader.o patchdata.o structdata.o  `wx-config --libs` `sdl2-config --libs` `pkg-config --libs SDL2_mixer` -o uzebox-patch-studio
uzebox-patch-studio.cpp: In member function ‘int UPSFrame::add_patch_command(const wxString&, const wxString&, const wxString&, int)’:
uzebox-patch-studio.cpp:579:28: error: conversion from ‘const wxString’ to ‘int’ is ambiguous
  579 |   patch_grid->SetCellValue(delay, row_num, 0);
      |                            ^~~~~
In file included from /usr/include/wx-3.2/wx/memory.h:15,
                 from /usr/include/wx-3.2/wx/object.h:19,
                 from /usr/include/wx-3.2/wx/wx.h:15,
                 from uzebox-patch-studio.cpp:3:
/usr/include/wx-3.2/wx/string.h:1592:5: note: candidate: ‘wxString::operator const wchar_t*() const’ (near match)
 1592 |     operator const wchar_t*() const { return c_str(); }
      |     ^~~~~~~~
/usr/include/wx-3.2/wx/string.h:1592:5: note:   no known conversion from ‘const wchar_t*’ to ‘int’
/usr/include/wx-3.2/wx/string.h:1595:5: note: candidate: ‘wxString::operator const char*() const’ (near match)
 1595 |     operator const char*() const { return c_str(); }
      |     ^~~~~~~~
/usr/include/wx-3.2/wx/string.h:1595:5: note:   no known conversion from ‘const char*’ to ‘int’
/usr/include/wx-3.2/wx/string.h:1599:5: note: candidate: ‘wxString::operator const void*() const’ (near match)
 1599 |     operator const void*() const { return c_str(); }
      |     ^~~~~~~~
/usr/include/wx-3.2/wx/string.h:1599:5: note:   no known conversion from ‘const void*’ to ‘int’
In file included from /usr/include/wx-3.2/wx/grid.h:14,
                 from uzebox-patch-studio.cpp:8:
/usr/include/wx-3.2/wx/generic/grid.h:2238:28: note:   initializing argument 1 of ‘void wxGrid::SetCellValue(int, int, const wxString&)’
 2238 |     void SetCellValue( int row, int col, const wxString& s );
      |                        ~~~~^~~
uzebox-patch-studio.cpp:580:28: error: conversion from ‘const wxString’ to ‘int’ is ambiguous
  580 |   patch_grid->SetCellValue(command, row_num, 1);
      |                            ^~~~~~~
/usr/include/wx-3.2/wx/string.h:1592:5: note: candidate: ‘wxString::operator const wchar_t*() const’ (near match)
 1592 |     operator const wchar_t*() const { return c_str(); }
      |     ^~~~~~~~
/usr/include/wx-3.2/wx/string.h:1592:5: note:   no known conversion from ‘const wchar_t*’ to ‘int’
/usr/include/wx-3.2/wx/string.h:1595:5: note: candidate: ‘wxString::operator const char*() const’ (near match)
 1595 |     operator const char*() const { return c_str(); }
      |     ^~~~~~~~
/usr/include/wx-3.2/wx/string.h:1595:5: note:   no known conversion from ‘const char*’ to ‘int’
/usr/include/wx-3.2/wx/string.h:1599:5: note: candidate: ‘wxString::operator const void*() const’ (near match)
 1599 |     operator const void*() const { return c_str(); }
      |     ^~~~~~~~
/usr/include/wx-3.2/wx/string.h:1599:5: note:   no known conversion from ‘const void*’ to ‘int’
/usr/include/wx-3.2/wx/generic/grid.h:2238:28: note:   initializing argument 1 of ‘void wxGrid::SetCellValue(int, int, const wxString&)’
 2238 |     void SetCellValue( int row, int col, const wxString& s );
      |                        ~~~~^~~
uzebox-patch-studio.cpp:581:28: error: conversion from ‘const wxString’ to ‘int’ is ambiguous
  581 |   patch_grid->SetCellValue(param, row_num, 2);
      |                            ^~~~~
/usr/include/wx-3.2/wx/string.h:1592:5: note: candidate: ‘wxString::operator const wchar_t*() const’ (near match)
 1592 |     operator const wchar_t*() const { return c_str(); }
      |     ^~~~~~~~
/usr/include/wx-3.2/wx/string.h:1592:5: note:   no known conversion from ‘const wchar_t*’ to ‘int’
/usr/include/wx-3.2/wx/string.h:1595:5: note: candidate: ‘wxString::operator const char*() const’ (near match)
 1595 |     operator const char*() const { return c_str(); }
      |     ^~~~~~~~
/usr/include/wx-3.2/wx/string.h:1595:5: note:   no known conversion from ‘const char*’ to ‘int’
/usr/include/wx-3.2/wx/string.h:1599:5: note: candidate: ‘wxString::operator const void*() const’ (near match)
 1599 |     operator const void*() const { return c_str(); }
      |     ^~~~~~~~
/usr/include/wx-3.2/wx/string.h:1599:5: note:   no known conversion from ‘const void*’ to ‘int’
/usr/include/wx-3.2/wx/generic/grid.h:2238:28: note:   initializing argument 1 of ‘void wxGrid::SetCellValue(int, int, const wxString&)’
 2238 |     void SetCellValue( int row, int col, const wxString& s );
      |                        ~~~~^~~
uzebox-patch-studio.cpp: In member function ‘int UPSFrame::add_struct_command(const wxString&, const wxString&, const wxString&, const wxString&, const wxString&, int)’:
uzebox-patch-studio.cpp:1090:29: error: conversion from ‘const wxString’ to ‘int’ is ambiguous
 1090 |   struct_grid->SetCellValue(type, row_num, 0);
      |                             ^~~~
/usr/include/wx-3.2/wx/string.h:1592:5: note: candidate: ‘wxString::operator const wchar_t*() const’ (near match)
 1592 |     operator const wchar_t*() const { return c_str(); }
      |     ^~~~~~~~
/usr/include/wx-3.2/wx/string.h:1592:5: note:   no known conversion from ‘const wchar_t*’ to ‘int’
/usr/include/wx-3.2/wx/string.h:1595:5: note: candidate: ‘wxString::operator const char*() const’ (near match)
 1595 |     operator const char*() const { return c_str(); }
      |     ^~~~~~~~
/usr/include/wx-3.2/wx/string.h:1595:5: note:   no known conversion from ‘const char*’ to ‘int’
/usr/include/wx-3.2/wx/string.h:1599:5: note: candidate: ‘wxString::operator const void*() const’ (near match)
 1599 |     operator const void*() const { return c_str(); }
      |     ^~~~~~~~
/usr/include/wx-3.2/wx/string.h:1599:5: note:   no known conversion from ‘const void*’ to ‘int’
/usr/include/wx-3.2/wx/generic/grid.h:2238:28: note:   initializing argument 1 of ‘void wxGrid::SetCellValue(int, int, const wxString&)’
 2238 |     void SetCellValue( int row, int col, const wxString& s );
      |                        ~~~~^~~
uzebox-patch-studio.cpp:1091:29: error: conversion from ‘const wxString’ to ‘int’ is ambiguous
 1091 |   struct_grid->SetCellValue(pcm, row_num, 1);
      |                             ^~~
/usr/include/wx-3.2/wx/string.h:1592:5: note: candidate: ‘wxString::operator const wchar_t*() const’ (near match)
 1592 |     operator const wchar_t*() const { return c_str(); }
      |     ^~~~~~~~
/usr/include/wx-3.2/wx/string.h:1592:5: note:   no known conversion from ‘const wchar_t*’ to ‘int’
/usr/include/wx-3.2/wx/string.h:1595:5: note: candidate: ‘wxString::operator const char*() const’ (near match)
 1595 |     operator const char*() const { return c_str(); }
      |     ^~~~~~~~
/usr/include/wx-3.2/wx/string.h:1595:5: note:   no known conversion from ‘const char*’ to ‘int’
/usr/include/wx-3.2/wx/string.h:1599:5: note: candidate: ‘wxString::operator const void*() const’ (near match)
 1599 |     operator const void*() const { return c_str(); }
      |     ^~~~~~~~
/usr/include/wx-3.2/wx/string.h:1599:5: note:   no known conversion from ‘const void*’ to ‘int’
/usr/include/wx-3.2/wx/generic/grid.h:2238:28: note:   initializing argument 1 of ‘void wxGrid::SetCellValue(int, int, const wxString&)’
 2238 |     void SetCellValue( int row, int col, const wxString& s );
      |                        ~~~~^~~
uzebox-patch-studio.cpp:1092:73: error: conversion from ‘const wxString’ to ‘int’ is ambiguous
 1092 | struct_grid->SetCellValue(patch == wxEmptyString && patch_names.size()?
      |                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^

 1093 |     *(patch_names.begin()) : patch, row_num, 2);
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                     

/usr/include/wx-3.2/wx/string.h:1592:5: note: candidate: ‘wxString::operator const wchar_t*() const’ (near match)
 1592 |     operator const wchar_t*() const { return c_str(); }
      |     ^~~~~~~~
/usr/include/wx-3.2/wx/string.h:1592:5: note:   no known conversion from ‘const wchar_t*’ to ‘int’
/usr/include/wx-3.2/wx/string.h:1595:5: note: candidate: ‘wxString::operator const char*() const’ (near match)
 1595 |     operator const char*() const { return c_str(); }
      |     ^~~~~~~~
/usr/include/wx-3.2/wx/string.h:1595:5: note:   no known conversion from ‘const char*’ to ‘int’
/usr/include/wx-3.2/wx/string.h:1599:5: note: candidate: ‘wxString::operator const void*() const’ (near match)
 1599 |     operator const void*() const { return c_str(); }
      |     ^~~~~~~~
/usr/include/wx-3.2/wx/string.h:1599:5: note:   no known conversion from ‘const void*’ to ‘int’
/usr/include/wx-3.2/wx/generic/grid.h:2238:28: note:   initializing argument 1 of ‘void wxGrid::SetCellValue(int, int, const wxString&)’
 2238 |     void SetCellValue( int row, int col, const wxString& s );
      |                        ~~~~^~~
uzebox-patch-studio.cpp:1094:29: error: conversion from ‘const wxString’ to ‘int’ is ambiguous
 1094 |   struct_grid->SetCellValue(loop_start, row_num, 3);
      |                             ^~~~~~~~~~
/usr/include/wx-3.2/wx/string.h:1592:5: note: candidate: ‘wxString::operator const wchar_t*() const’ (near match)
 1592 |     operator const wchar_t*() const { return c_str(); }
      |     ^~~~~~~~
/usr/include/wx-3.2/wx/string.h:1592:5: note:   no known conversion from ‘const wchar_t*’ to ‘int’
/usr/include/wx-3.2/wx/string.h:1595:5: note: candidate: ‘wxString::operator const char*() const’ (near match)
 1595 |     operator const char*() const { return c_str(); }
      |     ^~~~~~~~
/usr/include/wx-3.2/wx/string.h:1595:5: note:   no known conversion from ‘const char*’ to ‘int’
/usr/include/wx-3.2/wx/string.h:1599:5: note: candidate: ‘wxString::operator const void*() const’ (near match)
 1599 |     operator const void*() const { return c_str(); }
      |     ^~~~~~~~
/usr/include/wx-3.2/wx/string.h:1599:5: note:   no known conversion from ‘const void*’ to ‘int’
/usr/include/wx-3.2/wx/generic/grid.h:2238:28: note:   initializing argument 1 of ‘void wxGrid::SetCellValue(int, int, const wxString&)’
 2238 |     void SetCellValue( int row, int col, const wxString& s );
      |                        ~~~~^~~
uzebox-patch-studio.cpp:1095:29: error: conversion from ‘const wxString’ to ‘int’ is ambiguous
 1095 |   struct_grid->SetCellValue(loop_end, row_num, 4);
      |                             ^~~~~~~~
/usr/include/wx-3.2/wx/string.h:1592:5: note: candidate: ‘wxString::operator const wchar_t*() const’ (near match)
 1592 |     operator const wchar_t*() const { return c_str(); }
      |     ^~~~~~~~
/usr/include/wx-3.2/wx/string.h:1592:5: note:   no known conversion from ‘const wchar_t*’ to ‘int’
/usr/include/wx-3.2/wx/string.h:1595:5: note: candidate: ‘wxString::operator const char*() const’ (near match)
 1595 |     operator const char*() const { return c_str(); }
      |     ^~~~~~~~
/usr/include/wx-3.2/wx/string.h:1595:5: note:   no known conversion from ‘const char*’ to ‘int’
/usr/include/wx-3.2/wx/string.h:1599:5: note: candidate: ‘wxString::operator const void*() const’ (near match)
 1599 |     operator const void*() const { return c_str(); }
      |     ^~~~~~~~
/usr/include/wx-3.2/wx/string.h:1599:5: note:   no known conversion from ‘const void*’ to ‘int’
/usr/include/wx-3.2/wx/generic/grid.h:2238:28: note:   initializing argument 1 of ‘void wxGrid::SetCellValue(int, int, const wxString&)’
 2238 |     void SetCellValue( int row, int col, const wxString& s );
      |                        ~~~~^~~
make: *** [<builtin>: uzebox-patch-studio] Error 1
```

**Comment by artcfox** [comment]
I created a PR that allows uzebox-patch-studio to build on Debian 12 against libwxgtk3.2-dev: https://github.com/flaviozavan/uzebox-patch-studio/pull/5

**Comment by flaviozavan** [comment]
Merged #5
